### ISSUE TITLE
integration to aws credential_process

### ISSUE THREAD

**Issue by tianci86** [venth/aws-adfs#112]
Hi, 

I am trying to integrate to AWS CodeCommit. Whenever the user performs a git pull, it would authenticate with AD FS and STS and use the token to access CodeCommit. I would seek your help on this implementation.

Unfortunately, I have tried a few commands but i could not get it working

This is the configuration i have set inside my .aws/config file. I have also tried without --stdout but to no avail

[profile adfs]
credential_process = aws-adfs login --adfs-host adfs.host.com --provider-id urn:amazon:webservices --role-arn arn:aws:iam::123456789098:role/AWS_ROLE --no-ssl-verification --profile adfs --region eu-central-1 --session-duration 3600 --stdout

.gitconfig:
	helper = !aws --profile adfs codecommit credential-helper $@

**Comment by darnscott** [comment]
The --stdout flag needs to add `"Version": 1` in the json output ([documentation ref](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes)).
It would also be nice if the session expiration could be included in the JSON output as a ISO8601 formatted timestamp, which causes the credentials to automatically be refreshed.

**Comment by thomasgreensmith** [comment]
I ran into this issue while trying to use credential_process with AWS Toolkit for VSCode. 

I had to modify login.py with the following changes. 

Line 229 
` else:
        _store(config, aws_session_token)
        _emit_json(aws_session_token)
        #_emit_summary(config, aws_session_duration) `

Line 237 
` u"""{{"AccessKeyId": "{}", "SecretAccessKey": "{}", "SessionToken": "{}", "Version": 1}}""".format( `

this will now store credentials in .credentials file AND emit the correct json (with version)
