### ISSUE TITLE
Support AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by rinrinne** [venth/aws-adfs#123]
aws-adfs seems not to refer AWS_DEFAULT_PROFILE as default value of --profile option.

AWS CLI gets default profile from AWS_DEFAULT_PROFILE if defined.
Otherwise profile "default" is used.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html#using-profiles

I know botocore supports AWS_PROFILE. session.profile can have the same value as AWS_PROFILE if no --profile option specified. but according to document, it can be used within script only.
This means AWS_PROFILE or session.profile represents **current** profile. Maybe this allows CLI to be able to handle multiple profile within a command.

So I think it is the best solution to get default value of ---profile option from AWS_DEFAULT_PROFILE.

I already sent PR #122 regarding this issue.
(Sorry, I missed to check contribution guide before PR)

**Comment by pdecat** [comment]
Resolved by https://github.com/venth/aws-adfs/pull/122
