### ISSUE TITLE
ERROR: Cannot extract roles from response

### ISSUE THREAD

**Issue by kellermartin13** [venth/aws-adfs#128]
I'm just setting up aws-adfs for the first time, and I'm getting this error before and after the username/password prompt:
```
2019-07-31 14:58:28,341 [authenticator authenticator.py:authenticate] [2183-MainProcess] 
[140735538242432-MainThread] - ERROR: Cannot extract roles from response
```
This is happening regardless of the username or password I use. I haven't seen this error posted anywhere else. I see in the code this error comes up when the response != 200. I'm not receiving any push from DUO, so it doesn't seem like it's authenticating against LDAP. I wonder if something is wrong with my setup? 

aws-adfs version 1.17.0
python version 2.7.10

**Comment by kellermartin13** [comment]
Update for anyone stumbling across this: I was able to fix this by adding the flag "--no-sspi" to the end of the aws-adfs login request.
```
aws-adfs login --adfs-host=<my.host> --role-arn <my::role> --no-sspi
```
I'd link the documentation on this, but I don't know if it exists. Hope this helps someone!

**Comment by kfattig** [comment]
I believe this is a duplicate of https://github.com/venth/aws-adfs/issues/126 .  ADFS seems to be picky about user-agent, and the behavior varies depending on environment.

Allowing more granular control of user-agent, and maybe handling it as a config option would go a long way to addressing this, but would be probably break backwards compatibility as default behaviors would change.  I don't think I can deliver this without a test environment.
