### ISSUE TITLE
Duo Yubi(U2F)

### ISSUE THREAD

**Issue by andrewjlowery** [venth/aws-adfs#133]
I am receiving an error when trying to use the new u2f function to auth.

click.exceptions.ClickException: There was an issue during retrieval of a code entered into the device. The error response: {"stat": "OK", "response": {"status_code": "deny", "status": "Login request denied.", "result": "FAILURE", "reason": "Error"}}

I have raised a case with Duo, but maybe there is something that I am doing wrong.

Yubikey version: YubiKey 5 Nano

**Comment by andrewjlowery** [comment]
I have received feedback from Duo, as below:-

The back end logs show that the denials are occurring because:
"u2f_finish rejected: AuthenticationRejectedException('Bad origin received.',)"
and 
"Frame request Referer not like api-*.duosecurity.com"

As this is being generated from a non-supported integration, we are unable to identify the direct cause. The integration being used appears to be not generating the expected referer format.

**Comment by pdecat** [comment]
Hi @andrewjlowery, do you still have this issue?

If so, you should be able to get more details about what's going on by adding `--verbose` to your `aws-adfs login` command, e.g. `aws-adfs --verbose login ...`

**Comment by andrewjlowery** [comment]
@pdecat Thanks for your reply, when I run the aws-adfs using the --verbose I get a rejection.

![image](https://user-images.githubusercontent.com/32837706/69964034-6d3fad00-1509-11ea-8619-5c8057c359ca.png)

And speaking with Duo they suggested 'The back end logs show that the denials are occurring because:
"u2f_finish rejected: AuthenticationRejectedException('Bad origin received.',)"
and
"Frame request Referer not like api-*.duosecurity.com" '

If this process works for you then maybe its an issue with how I am registering my Yubikey or it is configured?

**Comment by pdecat** [comment]
You should have traces of the HTTP requests / responses happening before that.
Could you share the complete logs as [a gist](https://gist.github.com/)?

**Be careful to redact all sensitive content such as login, tokens, etc.**
