### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by danmx** [venth/aws-adfs#137]
Did you consider adding it to [homebrew](https://brew.sh/)?

**Comment by venth** [comment]
Hmm, I'm not sure about homebrew. Homebrew works only on osx. PIP on the other hand is system agnostic. What would be the brought value, if we will introduce homebrew?

**Comment by danmx** [comment]
It would be easier to install `aws-adfs` on macOS since it would be already isolated by `homebrew` like it does with [`aws-cli`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb).

**Comment by venth** [comment]
I don’t have any experience with homebrew package creation. Would you like to create PR that would provide such packaging?

**Comment by twillowman** [comment]
Homebrew pulls from package repositories, so no change would be needed to this project. It's a matter of creating a Homebrew formula, as documented here: https://docs.brew.sh/Adding-Software-to-Homebrew.

As such, I recommend closing this issue and opening one here in the Homebrew core project (https://github.com/Homebrew/homebrew-core/issues).
