### ISSUE TITLE
Add Python scripts compatibility

### ISSUE THREAD

**Issue by zevektor** [venth/aws-adfs#139]
Hi,

I would like to use this project as a python dependency in a GUI application. 
I'm finding very difficult to call the login function directly because the click decorators make the original function unusable.

Would you consider to decouple click functions from the original functions?

Something like this should work:
```python
@click_decorators
def function(arg1, arg2, argn):
    inner_function(arg1, arg2, argn)

def inner_function(arg1, arg2, argn):
    # actual logic here
```

Alternatively, is there any other way to interact with the python APIs without simulating a command-line call from the python script?

Thanks

**Comment by pdecat** [comment]
Hi, you should be able to call the original function with click's `Command.invoke()` method, see:
* https://click.palletsprojects.com/en/8.0.x/api/#click.Command.invoke
* https://github.com/pallets/click/blob/8.0.1/src/click/core.py#L1393
