### ISSUE TITLE
Login issues solved by changing the code and parameters

### ISSUE THREAD

**Issue by alFReD-NSH** [venth/aws-adfs#142]
I would normally make a pull request but I wasn't sure what's the best direction to go forward with this. To get this to work with my setup, I had to add `&RedirectToIdentityProvider=AD+AUTHORITY` to the [`IDP_ENTRY_URL`](https://github.com/venth/aws-adfs/blob/1.19.1/aws_adfs/html_roles_fetcher.py#L21) and also setting [AuthMethod](https://github.com/venth/aws-adfs/blob/1.19.1/aws_adfs/html_roles_fetcher.py#L77) as `'FormsAuthentication'`.

Setting `--provider-id` to `FormsAuthentication` didn't work for me as it only works with `urn:amazon:webservices` which is the default.

**Comment by rirze** [comment]
+1, I had to internally set `data['AuthMethod'] = 'FormsAuthentication'` before the POST command to get it to work. If there's a way to specify this option at the command line, that would be great!

**Comment by pdecat** [comment]
This should be resolved by https://github.com/venth/aws-adfs/pull/151 which was released in v1.24.0: https://github.com/venth/aws-adfs/releases/tag/1.24.0
