### ISSUE TITLE
Potential dependency conflicts between aws-adfs and botocore

### ISSUE THREAD

**Issue by NeolithEra** [venth/aws-adfs#148]
Hi, as shown in the following full dependency graph of  **_aws-adfs_**, **_aws-adfs_** requires **_botocore >=1.12.6_** ， while the installed version of **_boto3_**(1.10.23) requires _**botocore >=1.13.23,<1.14.0**_.

According to Pip's _“first found wins”_ installation strategy, _**botocore 1.13.23**_ is the actually installed version.  

Although the first found package version _**botocore 1.13.23**_ just satisfies the later dependency constraint （_**botocore >=1.13.23,<1.14.0**_), it will lead to a build failure once developers release a newer version of bleach.

### Dependency tree--------
```
aws-adfs - 1.21.1
| +- boto3(install version:1.10.23 version range:>=1.9.6)
| | +- botocore(install version:1.13.23 version range:>=1.13.23,<1.14.0)
| | | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| | +- s3transfer(install version:0.2.1 version range:>=0.2.0,<0.3.0)
| | | +- botocore(install version:1.13.23 version range:<2.0.0,>=1.12.36)
| | | | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | | | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| +- botocore(install version:1.13.23 version range:>=1.12.6)
| | +- docutils(install version:0.15.2 version range:>=0.10,<0.16)
| | +- jmespath(install version:0.9.4 version range:<1.0.0,>=0.7.1)
| +- click(install version:7.0 version range:*)
| +- configparser(install version:4.0.2 version range:*)
| +- fido2(install version:0.7.3 version range:*)
| | +- cryptography(install version:2.8 version range:>=1.5)
| | +- six(install version:1.13.0 version range:*)
| | +- uhid-freebsd(install version:1.2.1 version range:>=1.2.1)
| +- lxml(install version:4.4.1 version range:*)
| | +- cython(install version:0.29.14 version range:>=0.29.7)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_botocore <2.0.0_**.
2.	Ask your upstream project **_boto3_** to lose the version range of **_botocore_** to be **_>=1.13.23_**, and **_s3transfer_** to lose the version range of **_botocore_** to be **_>=1.12.36_**.

@venth Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by venth** [comment]
I thank we should go with the first solution. What do you think @pdecat?

**Comment by pdecat** [comment]
Hi @venth, I'm not sure there's any need to hurry and fix anything.

FWIW, I've initiated a migration to poetry that should help resolve dependencies issues: https://github.com/pdecat/aws-adfs/blob/poetry/

@NeolithEra, are you a bot? Your github activity only shows similar issue reporting :roll_eyes:   https://github.com/NeolithEra?tab=overview. Also, what did you mean by _bleach_?

**Comment by venth** [comment]
@pdecat, if you’re right then it would be smart attempt to inject malicious code 🤔

**Comment by NeolithEra** [comment]
@venth @pdecat Thank you for your quick feedback.
I am a researcher in software dependency management area.
We are trying to help developers find dependency conflict issues in the Python world.
Here is our related research work: http://faculty.neu.edu.cn/swc/wangying/Paper/Watchman.pdf

We just identify a dependency conflict in **_aws-adfs_** project, by analyzing the overall Pypi ecosystem.
Keeping the long-term health of open source projects is our common goal.


Thank you very much.

Best,
Neolith

**Comment by NeolithEra** [comment]
By the way, poetry is a very good tool that can solve part of these dependency hell problems.
However, poetry can only work well in the case that the required version constraints of the conflicting packages have an intersection.

When you migrate to poetry, please still pay attention to the dependency issues.

Happy new year!

**Comment by pdecat** [comment]
Hi @NeolithEra, good to hear :)

I've submitted #149 to drop the boto3 dependency altogether.

**Comment by venth** [comment]
@NeolithEra, thanks for sharing with us your findings 👍
