### ISSUE TITLE
Duo authentication not working with later versions of aws-adfs

### ISSUE THREAD

**Issue by tongak** [venth/aws-adfs#157]
I receive the following error when using aws-adfs version 1.24.1 with duo enabled.

Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/login.py", line 167, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config, config.adfs_user, password)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 34, in authenticate
    principal_roles, assertion, aws_session_duration = extract_strategy()
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 114, in extract
    return duo_auth.extract(html_response, config.ssl_verification, config.u2f_trigger_default, session)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/_duo_authenticator.py", line 54, in extract
    ssl_verification_enabled
ValueError: not enough values to unpack (expected 4, got 3)

When I am using aws-adfs version 1.12.3 the duo push authentication works fine.

I am using the following login command.

aws-adfs login --adfs-host=my.adfs.host --ssl-verification --session-duration 14400 --no-sspi

**Comment by psiri** [comment]
Have the same issue, it seems like this is related to lack of support for DUO bypass networks.

1.   If we authenticate from any non-bypassed networks (Starbucks, home office, etc) DUO successfully triggers the MFA method and the user can login successfully.

2.  If the user moves to a DUO-bypassed network (corp WiFi, VPN, etc) the MFA method is not triggered and the script fails. The 4th (expected) value is likely the MFA auth result

**Comment by tongak** [comment]
After doing some testing it seems the change happened between version 1.17.0 and 1.18.0. From version 1.18.0 and on I can not get the duo push notification, instead I just get the error above.

**Comment by pdecat** [comment]
Hi,

> After doing some testing it seems the change happened between version 1.17.0 and 1.18.0. From version 1.18.0 and on I can not get the duo push notification, instead I just get the error above.

Oops, I must have introduced that issue with https://github.com/venth/aws-adfs/pull/127, sorry.

I've tentatively submitted https://github.com/venth/aws-adfs/pull/160 to try to resolve this issue.

As I cannot reproduce the issue, could you please test the `fix_157_duo` branch?

To install that branch with pip at the system level in /usr/local:
```
# pip install git+https://github.com/venth/aws-adfs@fix_157_duo
```

To install that branch with pip in your home directory:
```
# pip install --user git+https://github.com/venth/aws-adfs@fix_157_duo
```

To install that branch with pipx in an isolated virtualenv:

```
# pipx install --force git+https://github.com/venth/aws-adfs@fix_157_duo
```

**Comment by tongak** [comment]
I have installed the above branch. I am getting a different error now. I get prompted for the password and I enter my password. I starts the next step of sending request, but then errors out.

**2020-03-12 09:43:02,037 [authenticator authenticator.py:authenticate] [1133-MainProcess] [140069562877760-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Password:
Sending request for authentication
2020-03-12 09:43:14,524 [authenticator authenticator.py:authenticate] [1133-MainProcess] [140069562877760-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
This account does not have access to any roles**

When I would get this error before I would have to add --no-sspi to the command line, but it is part of the command line.

**Comment by pdecat** [comment]
@tongak you should be able to get more details about what's going on by adding `--verbose` to your `aws-adfs login` command, e.g. `aws-adfs --verbose login ...`.

Note: you should have traces of the HTTP requests / responses that are happening.
In case you want to share some parts here, *be careful to redact all sensitive content such as login, tokens, etc*.

**Comment by tongak** [comment]
We figured it out and it was our fault. Our duo admin denied access to linux devices. For some strange reason up until version 1.18.0 aws-adfs was showing up as mac osx device, which is why it worked. Then 1.18.0 and beyond it shows up as a linux device and that is when I was having problems. Thanks @pdecat for your help. I actually found the error when using the verbose option.
