### ISSUE TITLE
automate aws-adfs with expect

### ISSUE THREAD

**Issue by brmakana** [venth/aws-adfs#16]
Hello,

I'm trying to automate logging in with aws-adfs, using expect. Has anyone managed to do this? I have not; so far I have:

```
#!/usr/bin/expect -f
spawn aws-adfs login --adfs-host my.host.com
set timeout 30
expect -r "Username: $"
send "$::env(username)\r"
expect -r "Password: $"
send "$::env(password)\r"
```

(assuming I have the user/pass in env vars) but it appears the password part gets skipped.

**Comment by venth** [comment]
I'll look into it.

**Comment by venth** [comment]
This script should do the thing:
`
spawn aws-adfs login --adfs-host=my.adfs.host
set timeout 30

expect {
  "Username: $" {
    send "$::env(username)\r"
    expect -r "Password: $"
    send "$::env(password)\r"
    exp_continue
  }

  "Selection: $" {
    send "$::env(selection)\r"
    exp_continue
  }
}
```

**Comment by brmakana** [comment]
That worked great, thanks!
