### ISSUE TITLE
Getting the below Error

### ISSUE THREAD

**Issue by rpsadarangani** [venth/aws-adfs#161]
Hello,

I am trying to use aws-adfs, but I am getting the below error.

click.exceptions.ClickException: Cannot begin authentication process. The error response: {"message": "Please select an authentication method.", "stat": "FAIL"}

**Comment by zhernovs** [comment]
Hi, you should update to the latest version. It was fixed in https://github.com/venth/aws-adfs/pull/158

**Comment by rpsadarangani** [comment]
Hi I tried but got the same error.

**Comment by ArthurKantor** [comment]
still broken in 1.24.5
