### ISSUE TITLE
Support for Passcode

### ISSUE THREAD

**Issue by zhernovs** [venth/aws-adfs#162]
In the latest version it's now available to choose auth method for DUO if default one not chosen. 
However, despite the fact that it now recognizes the Passcode method, it still works with push only. 
```
Sending request for authentication
Waiting for additional authentication
No default authentication method configured.
Please enter your desired authentication method (Ex: Duo Push): Passcode
Triggering authentication method: 'Passcode'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zhernovs/.local/lib/python2.7/site-packages/aws_adfs/_duo_authenticator.py", line 132, in _perform_authentication_transaction
    ssl_verification_enabled
  File "/home/zhernovs/.local/lib/python2.7/site-packages/aws_adfs/_duo_authenticator.py", line 565, in _begin_authentication_transaction
    u'Cannot begin authentication process. The error response: {}'.format(response.text)
ClickException: Cannot begin authentication process. The error response: {"message": "Please enter a passcode.", "stat": "FAIL"}
```

Please add functionality to enter passcode in that case. Some devices just don't support Duo-push.

**Comment by lincolnatwood** [comment]
In _duo_authenicatory.py, it is possible to use Passcode with the following changes (or is for me). I didn't dig too deep. I decided to use the preferred_device input as the passcode entry and hard-code the phone1 device.

Line 345 needs 'allow' added:
`        if json_response['response']['status_code'] not in ['answered', 'calling', 'pushed', 'u2f_sent', 'allow']:`

After line 553: 
`        click.echo("Triggering authentication method: '{}'".format(preferred_factor), err=True)
        if "Passcode" not in preferred_factor:
            click.echo("Device triggered.")
            response = session.post(
                prompt_for_url,
                verify=ssl_verification_enabled,
                headers=_headers,
                data={
                    'sid': sid,
                    'factor': preferred_factor,
                    'device': preferred_device,
                    'out_of_date': ''
                }
            )
        else:
            click.echo("Passcode triggered.")
            response = session.post(
                prompt_for_url,
                verify=ssl_verification_enabled,
                headers=_headers,
                data={
                    'sid': sid,
                    'device': 'phone1',
                    'factor': preferred_factor,
                    'passcode': preferred_device,
                    'out_of_date': '',
                    'days_out_of_date': '',
                    'days_to_block': 'None'
                }
            )`

**Comment by lincolnatwood** [comment]
click.echo("Triggering authentication method: '{}'".format(preferred_factor), err=True)
        if "Passcode" not in preferred_factor:
            click.echo("Device triggered.")
            response = session.post(
                prompt_for_url,
                verify=ssl_verification_enabled,
                headers=_headers,
                data={
                    'sid': sid,
                    'factor': preferred_factor,
                    'device': preferred_device,
                    'out_of_date': ''
                }
            )
        else:
            click.echo("Passcode triggered.")
            response = session.post(
                prompt_for_url,
                verify=ssl_verification_enabled,
                headers=_headers,
                data={
                    'sid': sid,
                    'device': 'phone1',
                    'factor': preferred_factor,
                    'passcode': preferred_device,
                    'out_of_date': '',
                    'days_out_of_date': '',
                    'days_to_block': 'None'
                }
            )

**Comment by lincolnatwood** [comment]
In _duo_authenicatory.py, it is possible to use Passcode with the following changes (or is for me). I didn't dig too deep. I decided to use the preferred_device input as the passcode entry and hard-code the phone1 device.

Line 345 needs 'allow' added:
`if json_response['response']['status_code'] not in ['answered', 'calling', 'pushed', 'u2f_sent', 'allow']:`

At line 553:
```
click.echo("Triggering authentication method: '{}'".format(preferred_factor), err=True)
if "Passcode" not in preferred_factor:
    click.echo("Device triggered.")
    response = session.post(
        prompt_for_url,
        verify=ssl_verification_enabled,
        headers=_headers,
        data={
            'sid': sid,
            'factor': preferred_factor,
            'device': preferred_device,
            'out_of_date': ''
        }
    )
else:
    click.echo("Passcode triggered.")
    response = session.post(
        prompt_for_url,
        verify=ssl_verification_enabled,
        headers=_headers,
        data={
            'sid': sid,
            'device': 'phone1',
            'factor': preferred_factor,
            'passcode': preferred_device,
            'out_of_date': '',
            'days_out_of_date': '',
            'days_to_block': 'None'
        }
    )
```

**Comment by lincolnatwood** [comment]
Here's what worked for me:

Updates in _perform_authentication_transaction method:

Insert at line 134:
```
    if ('Passcode' in preferred_factor) and not use_u2f:
        passcode = click.prompt(text='Please enter your passcode (Ex: 123456)', type=str)        
    else: 
        passcode = ''
```
Updated call to _begin_authentication_transaction to pass passcode variable:
```
    transaction_id = _begin_authentication_transaction(
        duo_host,
        sid,
        preferred_factor,
        preferred_device,
        use_u2f,
        session,
        ssl_verification_enabled,
        passcode
    )
```

Updates in _begin_authentication_transaction method:

Updated def to include passcode
```
def _begin_authentication_transaction(duo_host, sid, preferred_factor, preferred_device, u2f_supported, session,
                                      ssl_verification_enabled, passcode):
```
Updated session.post to include passcode:
```
        response = session.post(
            prompt_for_url,
            verify=ssl_verification_enabled,
            headers=_headers,
            data={
                'sid': sid,
                'device': preferred_device,
                'factor': preferred_factor,
                'passcode': passcode,                    
                'out_of_date': ''
            }
        )
```
