### ISSUE TITLE
There was an issue when following the Duo result URL after authentication

### ISSUE THREAD

**Issue by danielletran** [venth/aws-adfs#168]
After sucessful AD auth and Duo Push, the following is returned 

Error: There was an issue when following the Duo result URL after authentication. The error response: {"stat": "FAIL", "message": "Your session has expired. Please try again."}

**Comment by awang35** [comment]
A colleague of mines found out a fix for this:

 It looks like the Duo API behavior has changed and the reuse of the SID value does not work anymore in multiple requests. The following changes use the SID value from the last request in the chain and fix the issue.

If you are using _duo_authenticator.py adding the following after line 249 should fix it.

sid=response.json()['response']["sid"]

**Comment by pdecat** [comment]
Hi,

if you still face the error, would you mind sharing some more details about the error you are facing?

You should be able to get more details about what's going on by adding `--verbose` to your `aws-adfs login` command, e.g. `aws-adfs --verbose login ...`.

Note: you should have traces of the HTTP requests / responses that are happening.
In case you want to share some parts here, **be careful to redact all sensitive content such as login, tokens, etc**.

**Comment by danielletran** [comment]
hi 
1.24.4 has resolved the issue for us.
