### ISSUE TITLE
Add an option to change the STS token duration

### ISSUE THREAD

**Issue by n-my** [venth/aws-adfs#17]
Now that we can specify an AWS console session duration using SAML 2.0 (see [here](https://aws.amazon.com/blogs/security/enable-your-federated-users-to-work-in-the-aws-management-console-for-up-to-12-hours/)) it would be nice to have an option to set the STS token duration in aws-adfs.

The idea is that if I can have a 12h session I don't want to re-log every hour because the STS token duration being hardcoded to 3600 seconds.

What do you think ?

**Comment by niravradia** [comment]
+1

**Comment by venth** [comment]
Let me look into that

**Comment by venth** [comment]
I've removed DurationSeconds limit counting that SessionDuration attribute in saml response will be honored. Unfortunately, it looks that sts API ignores this attribute and sticks to one hour limit. Providing explicit longer DurationSeconds results in validation error.

I've created feature branch: `feature/STS-token-duration` so you may browse implementation by yourself. Short info for hacking: 
* create virtual environment
* pip install --editable ./
* use aws-adfs --verbose login ...

If you have any suggestions for extending session time I'm open ;)

**Comment by venth** [comment]
The documentation states that maximum time for a credentials got from assume role with saml is: 3600 seconds 
`http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html`

> DurationSeconds
The duration, in seconds, of the role session. The value can range from 900 seconds (15 minutes) to 3600 seconds (1 hour). By default, the value is set to 3600 seconds. An expiration can also be specified in the SAML authentication response's SessionNotOnOrAfter value. The actual expiration time is whichever value is shorter.
Note
This is separate from the duration of a console session that you might request using the returned credentials. The request to the federation endpoint for a console sign-in token takes a SessionDuration parameter that specifies the maximum length of the console session, separately from the DurationSeconds parameter on this API. For more information, see Enabling SAML 2.0 Federated Users to Access the AWS Management Console in the IAM User Guide.
Type: Integer
Valid Range: Minimum value of 900. Maximum value of 3600.
Required: No

**Comment by n-my** [comment]
Thank you @venth for having investigating this one. I am closing the issue until AWS changes the max value.

**Comment by venth** [comment]
Thank you 😀
