### ISSUE TITLE
Ability to change the URN in html_roles_fetcher.py

### ISSUE THREAD

**Issue by kwhitlock** [venth/aws-adfs#18]
Hi

Is there are a way of overriding the urn url on line 26 of html_roles_fetcher.py, from calling aws-adfs on the command line?

Currently its hard coded to webservices, but we use many different urn names.

Ta,

**Comment by venth** [comment]
Currently there isn't any way to change the urn url. How shall the usage scenario look like? Could you give an example?

**Comment by venth** [comment]
OK, I understood what you require. Please, correct the code so that travis will finish build with success.

**Comment by kwhitlock** [comment]
Done 👍

**Comment by venth** [comment]
Merged and released as 0.2.1. Could I ask for closing the issue?

**Comment by kwhitlock** [comment]
Many thanks. :)
