### ISSUE TITLE
AWS session caching is not implemented, ADFS is called every time

### ISSUE THREAD

**Issue by Tantalon** [venth/aws-adfs#182]
When using aws-adfs with credential_process it makes a call to ADFS every time an AWS call is made (e.g. this is three ADFS calls: aws s3 ls; aws s3 cp; aws s3 ls). For me this adds 1 second to each AWS call.

According to the [AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html), credential_process is responsible for caching the session token, and this isn't happening.

In aws-adfs if --stdout is specified, then ~/.aws/credentials isn't updated, so next time credential_process is called again, and as it has no access to a session token, it in turn has to calling ADFS again. Based on "Remove storage of credentials, in favor of storing ADFS session cookies" I believe the intent is to reuse adfs_cookies. However, this only allows you to renew a token by calling ADFS again, the still active AWS session is lost.

I believe it's necessary to store the session even when using ~/.aws/adfs_cookies. This way back-to-back CLI calls to be made quickly using the same AWS session, and only once that has expired do we need to use adfs_cookies to obtain a new AWS session.

Edit: Removed suggestion that ~/.aws/credentials is the typical way to cache credentials because it doesn't appear to respect credential expiry.

**Comment by Tantalon** [comment]
@brandond I'd appreciate your view on this as it relates to the ADFS session cookie functionality.

**Comment by likku123** [comment]
I believe the below error is because of broken session caching.
 An error occurred (AccessDenied) when calling the PutObject operation: No AWSAccessKey was presented.
I was able to perform aws s3 ls and other commands but failing for cp/sync.

**Comment by pdecat** [comment]
This has bothered me too for a long time, I'm looking at this now.

**Comment by Tantalon** [comment]
Tested with `pip3 install git+https://github.com/venth/aws-adfs.git@b61e7517bf52c0b35f011e25a911897a68cec12f`
aws-adfs calls have gone from 7 seconds to 300ms!
Thank you, this is awesome.
