### ISSUE TITLE
Please select an authentication method.

### ISSUE THREAD

**Issue by rodrigo-fss** [venth/aws-adfs#188]
Hello,

I am trying to use aws-adfs, but I am getting the below error.

click.exceptions.ClickException: Cannot begin authentication process. The error response: {"message": "Please select an authentication method.", "stat": "FAIL"}

Im not able to set the default DUO method so I rely on this functionality

**Comment by pdecat** [comment]
Hi, what is the complete `aws-adfs login` command you are using?

Make sure to redact confidential information like ADFS host and the sorts.

**Comment by alubneuski** [comment]
I have similar issue. 
```
click.exceptions.ClickException: Cannot begin authentication process. The error response: {"stat": "FAIL", "message": "Please select an authentication method."}
```
Here is my command line:
aws-adfs login --adfs-host xxx.xxx.xxx --no-sspi --profile=xxxxxxxx

Config file looks like this:
6 [xxxxxxx]
 7 region = us-west-2
 8 output = json
 9 adfs_config.ssl_verification = True
10 adfs_config.adfs_host = xxxxxx
11 adfs_config.provider_id = urn:amazon:webservices
12 adfs_config.sspi = False
13 adfs_config.u2f_trigger_default = False
14 adfs_config.session_duration = 28800
15 adfs_config.adfs_user = xxxxxxxxx

**Comment by pdecat** [comment]
I'm going to allow passing the authentication method and device to AWS ADFS as a CLI parameter, e.g.:

```
aws-adfs login --method  "Duo Push" --device "phone1"...
```

Other possible methods: `WebAuthn`, `Phone`
