### ISSUE TITLE
list output is too simple

### ISSUE THREAD

**Issue by SydOps** [venth/aws-adfs#20]
Currently the list output is too simple, I use it to set a default profile, but sometime I need switch to other account, which it doesn't make sense for me, if always list as default. 

can we have output with additional information, such as profile name, aws account alias and adfs_config.role_arn?

**Comment by venth** [comment]
Would you like to paste a mockup (could be formatted text), so it would be easier for me to see the results of the change?

**Comment by SydOps** [comment]
change from:

```
$ aws-adfs list
Available profiles:
    * default
```
to something like this, so I can easily know what's the current default profile. 

```
$ aws-adfs list
Available profiles:
    * default | adfs-xxx-nonprod | arn:aws:iam::xxxxxxxx:role/administrator
```

**Comment by SydOps** [comment]
Second, if I set `AWS_DEFAULT_PROFILE=xxx-nonprod` or `AWS_PROFILE=xxx-nonprod` environment variables
```
export AWS_DEFAULT_PROFILE=xxx-nonprod
export AWS_PROFILE=xxx-nonprod
```

I got error when run below command:

```
$ aws-adfs login --adfs-host adfs.example.com.au --region ap-southeast-2
....
botocore.exceptions.ProfileNotFound: The config profile (xxx-nonprod) could not be found
```

**Comment by SydOps** [comment]
pull request has been raised.

**Comment by SydOps** [comment]
PR has been merged.

**Comment by venth** [comment]
Released with version 0.2.2

**Comment by SydOps** [comment]
@venth 

Saw the codes you updated in `aws_adfs/list_profiles.py`, seems line 19 is not required any more. 

https://github.com/venth/aws-adfs/blob/master/aws_adfs/list_profiles.py#L19

**Comment by venth** [comment]
You're right 😄I'll fix it. Thanks.
