### ISSUE TITLE
Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4

### ISSUE THREAD

**Issue by SydOps** [venth/aws-adfs#22]
With default setting by aws-adfs, I can't download files from s3 buckets. 

>$ aws s3 cp s3://xxx/xxx.yml xxx.yml 

>download failed: s3://xxx/xxx.yml to xxx.yml An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4. You can enable AWS Signature Version 4 by running the command: aws configure set s3.signature_version s3v4

After run `aws configure set s3.signature_version s3v4`

Below lines are added to ~/.aws/config

```
s3 =
    signature_version = s3v4
```

So if I `aws-adfs reset` and `aws-adfs login` again, I lost the s3 setting in config file.

**Comment by venth** [comment]
`aws-adfs reset` works as designed - removes stored profile. I think that you expected that reset removes from a profile aws-adfs metadata. 

Perhaps current `aws-adfs reset` shall act as you expected and new sub-command `aws-adfs removes-profile` shall remove a profile?

**Comment by SydOps** [comment]
can we have one more option to enable s3 signature version when `aws-adfs login`?

**Comment by venth** [comment]
OK. I'll add this option with empty default value

**Comment by venth** [comment]
Released with version: 0.2.3

**Comment by SydOps** [comment]
Yes, work as expect. Thanks.

**Comment by SydOps** [comment]
@venth 

I faced a strange problem when enable `--s3-signature-version s3v4`. 

With above option enabled, when I run `aws s3 cp`, I got the file is same when I download it from aws console.  But when running in application (SDK) to get the file, for example, I run `terraform remote config`, I got an old file. 

If disable this option, the problem is gone.

**Comment by venth** [comment]
@SydOps I think it's rather related to way how boto is working, since the configuration is read by this library. aws-adfs just appends configuration and nothing more.
