### ISSUE TITLE
`login --role-arn "?"` not working on an existing profile

### ISSUE THREAD

**Issue by brightben1111** [venth/aws-adfs#227]
Before aws-adfs 2.0, one could do the following:

1. `aws-adfs login --profile foo --role-arn "?"` - to initialize profile `foo` and be able to select the role arn you want from a list.
2. `aws-adfs login --profile foo --role-arn "?"` - the same command again for the same profile, and get the same role select list _again_.

Now when using `--role-arn "?"` for subsequent logins on an already established profile, aws-adfs does not present the role list; instead it just re-uses whatever role was already present in the profile.

`aws-adfs reset` does not work to bring the role list back, you have to either go so far as to clear out the adfs cache in `~/.aws/adfs-cache` to get the role list back or wait for your adfs session to expire.

I checked with the last version before 2.0 (1.24.5) and the original behavior is still available.

**Comment by brightben1111** [comment]
bumping this because it's still an issue

**Comment by pdecat** [comment]
Hi @brightben1111, sorry for the trouble here. I've submitted https://github.com/venth/aws-adfs/pull/232 to disable caching if `role_arn` is not provided by configuration.

You should be able to test this PR with:

```
pipx install -f git+https://github.com/venth/aws-adfs@fix_cache_role_arn
```

**Comment by brightben1111** [comment]
hey @pdecat, sorry I never got around to testing your PR but as of v2.2.2 this issue is still present.

**Comment by brightben1111** [comment]
Confirmed it works this time, thank you!
