### ISSUE TITLE
--verbose flag fails when used with login --adfs-host.

### ISSUE THREAD

**Issue by eric-nord** [venth/aws-adfs#23]
--verbose flag doesn't seem to work:

aws-adfs login --verbose --adfs-host "https://XXXXXXXXXXX.XXX.XXX/adfs/ls/IdpInitiatedSignOn.aspx"
Error: no such option: --verbose

aws-adfs login --adfs-host "https://XXXXXXXXXXX.XXX.XXX/adfs/ls/IdpInitiatedSignOn.aspx" --verbose
Error: no such option: --verbose

**Comment by venth** [comment]
Hi @eric-nord 

login command doesn't have --verbose option. This option is a global one. Please look on help of login command:
`
aws-adfs login --help
Usage: aws-adfs login [OPTIONS]

  Authenticates an user with active directory credentials

Options:
  --profile TEXT                  AWS cli profile that will be authenticated.
                                  After successful authentication just use:
                                  aws --profile <authenticated profile>
                                  <service> ...
  --region TEXT                   The default AWS region that this script will
                                  connect
                                  to for all API calls
  --ssl-verification / --no-ssl-verification
                                  SSL certificate verification: Whether or not
                                  strict certificate
                                  verification is done,
                                  False should only be used for dev/test
  --adfs-host TEXT                For the first time for a profile it has to
                                  be provided, next time for the same profile
                                  it will be loaded from the stored
                                  configuration
  --output-format [json|text|table]
                                  Output format used by aws cli
  --provider-id TEXT              Provider ID, e.g urn:amazon:webservices
                                  (optional)
  --s3-signature-version [s3v4]   s3 signature version: Identifies the version
                                  of AWS Signature to support for
                                  authenticated requests. Valid values: s3v4
  --help                          Show this message and exit.
`

and aws-adfs:
`
aws-adfs --help
Usage: aws-adfs [OPTIONS] COMMAND [ARGS]...

Options:
  --version      Show current tool version
  -v, --verbose  Enables debug information on stdout. By default log level is
                 set on ERROR
  --help         Show this message and exit.

Commands:
  list   lists available profiles
  login  Authenticates an user with active directory...
  reset  removes stored profile
`
To enable verbosity in login execute:
`
aws-adfs --verbose login ...
`
Perhaps it makes sense to have verbose option for each command. Judging by this issue current placing of --verbose option is misleading. Probably it should be accessible for each command.
What do you think?

**Comment by eric-nord** [comment]
That does make sense after reviewing it on the help page again. Thank you for taking the effort to look into it. Adding the "To enable..." Line does make it more clear.
