### ISSUE TITLE
cache file truncation

### ISSUE THREAD

**Issue by mattmauriello** [venth/aws-adfs#234]
I was running into an issue where every credential fetch from boto/cli would result in a fetch back to adfs, rather than using cached credentials. i could see that the cache file was getting updated with EVERY call, the expires time incrementing every time. during troubleshooting, with some verbose output, i saw there was an error reading the cache file, and after looking at it a 2nd time, I noticed it ended like this:
`18:28:20 GMT"}, "RetryAttempts": 0}}tempts": 0}}`
because of the extra short string (12 characters total) after what should be the closing bracket, the json parser failed to parse it. this lead to an ADFS fetch, a write to the cache file, but again, it remains "corrupted". checking the code where it writes that file, I notice its opened with Create, Write, but NOT Truncate:
[here](https://github.com/venth/aws-adfs/blob/37170533fb340986e01c8d5248b817cf69097b92/aws_adfs/login.py#L568)
`with os.fdopen(os.open(cache_file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as f:`
so, it seems at some point some value was longer than typical (couldn't tell you why), but any subsequent write didn't overwrite ALL the content, leaving those 12 trailing bytes. In local testing, i added O_TRUNC to the open, and after subsequent run, the new credentials were written in a way that could be read by json decoder.
I'm curious if there was a deliberate reason for not including TRUNC in the open flags. if there is no reason to omit it, I'll be happy to issue a PR to add it, if you believe it's warranted.

Thanks,
-Matt

**Comment by pdecat** [comment]
Adding [O_TRUNC]( https://manpages.debian.org/bullseye/manpages-dev/open.2.en.html#O_TRUNC) sounds like the way to go, indeed.

Feel free to open a PR, thanks!
