### ISSUE TITLE
Add option to remove adfs Cookie that stores user account information

### ISSUE THREAD

**Issue by anthony-estevez-zefr** [venth/aws-adfs#26]
Hi, 

I was wondering if it would be possible to add an option that removes the adfs user account used so that we have the option to sign in with another user account.

**Comment by venth** [comment]
I think that the easies way is usage of different aws profiles. Like that:
`aws-adfs login --profile=user_foo ...`
`aws-adfs login --profile=user_bar ...`

Then you can execute any aws command using permissions of a specific user just by providing the profile. Like:
`aws --profile=user_foo <service> ...`
`aws --profile=user_bar <service> ...`

**Comment by anthony-estevez-zefr** [comment]
Great!
