### ISSUE TITLE
--region and --output-format flags don't seem to be working

### ISSUE THREAD

**Issue by anthony-estevez-zefr** [venth/aws-adfs#27]
Hello,

It seems a few flags aren't working.

> aws-adfs login --region=us-west-2 --adfs-host=SITE --output-format=text
Sending request for authentication
Waiting for additional authentication
Going for aws roles

        Prepared ADFS configuration as follows:
            * AWS CLI profile                   : 'default'
            * AWS region                        : 'eu-central-1'
            * Output format                     : 'json'
            * Provider ID                       : 'urn:amazon:webservices'
            * S3 Signature Version              : 'None'

**Comment by venth** [comment]
The issue here is that value provided via parameter in command line doesn't override the previously stored one.

**Comment by venth** [comment]
Fix delivered with version: 0.3.2

**Comment by anthony-estevez-zefr** [comment]
It's working great.
