### ISSUE TITLE
Duo Authentication fails for users who don't have a preferred Auth method.

### ISSUE THREAD

**Issue by cliv** [venth/aws-adfs#30]
While trying to authenticate to an ADFS 3.0 provider using duo auth I get the following error (With --verbose flag to aws-adfs)
```
2017-04-25 16:40:07,354 [connectionpool connectionpool.py:_make_request] [10680-MainProcess] [140176161351424-MainThread] - DEBUG: https://--sanitized--:443 "POST /frame/prompt HTTP/1.1" 200 61
2017-04-25 16:40:07,360 [_duo_authenticator _duo_authenticator.py:_begin_authentication_transaction] [10680-MainProcess] [140176161351424-MainThread] - DEBUG: Request:
        * url: https://--sanitized--/frame/prompt
        * headers: {'Content-Length': '152', 'Accept-Language': 'en', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/plain, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko', 'Connection': 'keep-alive', 'Cookie': '--sanitized--', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
    Response:
        * status: 200
        * headers: {'Content-Length': '61', 'Content-Security-Policy': "default-src 'self'; img-src 'self' https://notify.bugsnag.com ; connect-src 'self'", 'Strict-Transport-Security': 'max-age=31536000', 'Server': 'Duo/1.0', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store', 'Date': 'Tue, 25 Apr 2017 20:40:07 GMT', 'P3P': 'CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"', 'Content-Type': 'application/json'}
        * body: {"message": "Unknown authentication method.", "stat": "FAIL"}
    
Error: Cannot begin authentication process. The error response: {"message": "Unknown authentication method.", "stat": "FAIL"}
```

Once I logged in via browser, clicking 'settings' -> 'My Settings & Devices'  and setting an option in 'When I log in:' aws-adfs worked fine. 

After a bit of poking and troubleshooting, it looks like [/aws-adfs/_duo_authenticator.py](https://github.com/venth/aws-adfs/blob/master/aws_adfs/_duo_authenticator.py#L304-L307) looks for a preferred auth method and uses that in the form post back to Duo; if it's not set, the post to Duo contains a blank 'factor:' field and is considered invalid.

**Comment by venth** [comment]
Thanks for mentioning about this issue. At beginning I'll add to readme information that in case of du-security there is a need to setup preferred device. Then I'll add possibility to choose then device.

**Comment by venth** [comment]
I described the workaround provided by you and added the issue: #33 to deal with the situation when the preferred device is missing.

**Comment by venth** [comment]
Since the workaround is described and new issue is created, may I ask to close this one?

**Comment by cliv** [comment]
Absolutely - Thanks @venth!
