### ISSUE TITLE
adfs conflicts with default profile 

### ISSUE THREAD

**Issue by cougar2009** [venth/aws-adfs#37]
If mfa_serial exist in the default profile then it asks for an mfa_code after role selection [observed with DUO mfa]  

If role_arn exist in the default profile then after role selection it tries to authenticate with the role_arn from the existing default profile.

**Comment by venth** [comment]
I'll look into the code and find out, why duo is asked for code after role selection.

**Comment by venth** [comment]
@cougar2009 which profile did you use to authenticate against adfs? Default one? What value did you pass to `--profile` parameter of `aws-adfs` command?

**Comment by venth** [comment]
Despite several tries I wasn’t able to setup adfs and duo security to access my private account. I cannot create environment resembling one you use reproduce the issue. I’ll keep the issue till I’ll figure out how to setup adfs and duo

**Comment by venth** [comment]
Please reopen, if the bug still exists
