### ISSUE TITLE
Number Matching | Microsoft Authenticator

### ISSUE THREAD

**Issue by karrtikiyer** [venth/aws-adfs#371]
Our organisation has started using additional MFA option called `Number Matching`, where in a number gets displayed on screen which needs to be entered in the Microsoft MFA App.
Does anyone here know how we can configure AWS-ADFS to work with this new feature? So that number gets displayed on command line which we can enter on the MFA App?
This works fine via web browsers as the number appears on the web browser screen.
 https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match#enable-number-matching-using-graph-apis

**Comment by karrtikiyer** [comment]
Probably related issue: https://github.com/aws-azure-login/aws-azure-login/issues/266

**Comment by marcoscale98** [comment]
I have the same problem

**Comment by martinverup** [comment]
This would be a very simple fix. Just print the validEntropyNumber if it exists.

![Image](https://github.com/venth/aws-adfs/assets/956651/2643186b-831d-466e-99d4-d85ea125e56c)

**Comment by casimp** [comment]
Our company is now facing the same issue (and seeing the same behaviour described by @Reefersleep ). 

From https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match#enable-number-matching-using-graph-apis:

> Beginning May 8, 2023, number matching is enabled for all Authenticator push notifications. As relevant services deploy, users worldwide who are enabled for Authenticator push notifications will begin to see number matching in their approval requests. 

So, it looks like number matching has now been enabled/deployed for everyone using Authenticator push notifications.

**Comment by pdecat** [comment]
Resolved by #387
