### ISSUE TITLE
Support for Duo's "Remember Me" feature

### ISSUE THREAD

**Issue by cliv** [venth/aws-adfs#40]
Would it be possible to leverage Duo's "Remember me for x days" feature (I believe it's set via a cookie) to prevent having to continually use MFA on the same machine?

![image](https://cloud.githubusercontent.com/assets/2160736/26129570/b85d84c0-3a5e-11e7-9f12-6af8b7dd423c.png)

The ability to do so is optional, and controlled by the duo admin for the team, but if the checkbox exists, it would be great to be able to optionally set it, maybe via a run time switch (--duo-remember-me?).

**Comment by venth** [comment]
Cannot setup DUO to test the solution.
