### ISSUE TITLE
Error: Cannot begin authentication process. The error response: {"stat": "FAIL", "message_enum": 57, "data": {}}

### ISSUE THREAD

**Issue by william-mcdaniels** [venth/aws-adfs#411]
Getting this error after things were working fine a few days ago with the universal prompt and latest version.  Just trying to get more info on what might be needed on our side since the aws-adfs likely hasn't changed in a few days since last upgrade.

duo universal prompt was deployed last week and an aws-adfs update fixed the client side until today suddenly.

**Comment by william-mcdaniels** [comment]
Apparently the most recent change was Duo adapter for ADFS - upgraded to adfs3-2.0.0.  Happened last night.

**Comment by stryke** [comment]
I began seeing the same issue at UCSF this morning. I don't know any details about what specifically was upgraded, other than "Duo will upgrade to 'Duo Universal Prompt'” per the email that IT sent out today entitled "Today’s the Day: New Process for Duo Multi-Factor Authentication."

**Comment by william-mcdaniels** [comment]
Now the error has evolved to this one following the Universal prompt update:

Error: Cannot begin authentication process. The error response: {"stat": "FAIL", "message_enum": 57, "data": {}}
