### ISSUE TITLE
Script-ability

### ISSUE THREAD

**Issue by eikenb** [venth/aws-adfs#45]
Would you consider a pull request that added a way to make the call to aws-adfs non-interactive. I'm thinking a login argument that has it take accept the password from STDIN (like sudo -S) and another that lets you give the username on the command line.

Thought I'd ask to see if you'd be open to a PR before just diving into the code.

Thanks.

**Comment by eikenb** [comment]
I think it might be better to just have the stdin argument that takes a username/password pair. So it is one option and you eliminate weird states like having the password passed in but no username. Either separated by a newline, colon, or something similar.

**Comment by venth** [comment]
OK, please create PR. I'll look into it.

**Comment by eikenb** [comment]
Submitted the PR; #48

**Comment by venth** [comment]
PR #48 merged and released with version 0.3.6

**Comment by eikenb** [comment]
Great. Thanks!
