### ISSUE TITLE
Clear IAM role from config

### ISSUE THREAD

**Issue by holmesjr** [venth/aws-adfs#5]
It would be nice to have a CLI option to clear the saved IAM role from the config, so we could swap between roles without having to edit the config file manually. I can send a pull request if you're happy to consider the change.

**Comment by venth** [comment]
There is the reset command. I use reset to completely wipeout the specific aws profile. Would you like to describe the usage scenario, you have in mind, so the need would be clearer for me?

**Comment by holmesjr** [comment]
Ah, my mistake. I used the `default` profile in my auth but then reset without specifying a profile (so it defaulted to `adfs`).

**Comment by venth** [comment]
Perhaps I should improve the description. If you have any suggestion on that I would be glad 😄

**Comment by holmesjr** [comment]
Happy that it was PEBKAC over here.
