### ISSUE TITLE
Duo MFA: please add documentation for how to use it.

### ISSUE THREAD

**Issue by cytopia** [venth/aws-adfs#51]
I would like to use `aws-adfs` with DUO (MFA), however I could not find any documentation how to use it.
Could you please add some documentation or howto.

**Comment by venth** [comment]
There is no special configuration required to use aws-adfs with adfs server with DUO security enabled. Perhaps besides setup preferred auth method in duo-sercurity settings (settings' -> 'My Settings & Devices').

Just execute command `aws-adfs login --adfs-host=<your adfs host address>` and follow instructions presented on the screen.

**Comment by cytopia** [comment]
Thanks, I thought it was an `aws-adfs` setting, rather than the `adfs-host` itself.
