### ISSUE TITLE
When using two roles error: This account does not have access to any roles

### ISSUE THREAD

**Issue by anthoneous** [venth/aws-adfs#55]
As of 0.3.14 it appears that you cannot choose a role if you have more than one assigned.
```
11:23 AM: MAC: > aws-adfs login
Sending request for authentication
Waiting for additional authentication
Going for aws roles
This account does not have access to any roles
```

With only one role:
```
11:14 AM: MAC: > aws-adfs login
Sending request for authentication
Waiting for additional authentication
Going for aws roles

        Prepared ADFS configuration as follows:
            * AWS CLI profile                   : 'default'
            * AWS region                        : 'us-east-1'
            * Output format                     : 'json'
            * SSL verification of ADFS Server   : 'ENABLED'
            * Selected role_arn                 : 'arn:aws:iam::#########:role/ROLE'
            * ADFS Server                       : 'sso.#####.com'
            * ADFS Session Duration in seconds  : '28800'
            * Provider ID                       : 'urn:amazon:webservices'
            * S3 Signature Version              : 'None'
```

Version 0.3.3 with roles working:
```
11:43 AM: MAC: > aws-adfs login --adfs-host sso.###.com
Sending request for authentication
Waiting for additional authentication
Going for aws roles
Please choose the role you would like to assume:
    [ ROLE1               -> 0 ]: arn:aws:iam::#########:role/Role1
    [ ROLE2............... -> 1 ]: arn:aws:iam::#########:role/Role2
```

**Comment by anthoneous** [comment]
Appears to be related to https://github.com/venth/aws-adfs/issues/50. I just tested on version 0.3.9.

**Comment by anthoneous** [comment]
python version 2.7.14 -- installed via pyenv.

**Comment by venth** [comment]
I see that you use the default profile. Can you perform `aws-adfs reset —profile=default` before login?

**Comment by anthoneous** [comment]
Resetting the profile has not resolved the issue.

```
03:28 PM: MAC: > aws-adfs reset --profile=default
Profile: 'default' has been wiped out
03:28 PM: MAC: > aws-adfs login --adfs-host sso.####.com
Sending request for authentication
Waiting for additional authentication
Going for aws roles
This account does not have access to any roles
03:28 PM: MAC: > aws-adfs --version
0.3.14
```

**Comment by venth** [comment]
Please send / paste the debug logs from login command (`aws-adfs —debug login —adfs-host=your.host`)

**Comment by anthoneous** [comment]
I've attached the logs as requested.

[adfs-debug.log](https://github.com/venth/aws-adfs/files/1353749/adfs-debug.log)

**Comment by anthoneous** [comment]
After reviewing the debug log, you can see that the roles are visible.

**Comment by venth** [comment]
Thanks for the log. I'll look into it.

**Comment by venth** [comment]
I thought, I found the case. Tests proved I was wrong. Investigation still in progress.

**Comment by anthoneous** [comment]
Here's the new log for 0.3.16:
```
03:16 PM: anthony.estevez@MACC02RH6CNG8WN: > aws-adfs --verbose login --adfs-host sso.zefr.com > adfs-debug.log
This account does not have access to any roles
[adfs-debug.log](https://github.com/venth/aws-adfs/files/1357515/adfs-debug.log)

```

**Comment by venth** [comment]
Thanks for the log.

**Comment by venth** [comment]
I think that I narrowed and corrected the issue. Please, use version: 0.3.17. If the issue will prevail, please share the logs.

**Comment by anthoneous** [comment]
Still no luck. I've uploaded the new logs.

[adfs-log.log](https://github.com/venth/aws-adfs/files/1360786/adfs-log.log)

**Comment by venth** [comment]
Thanks to your patience I managed to identify the error causing scenario. An user with one or multiple roles grouped under one aws account cannot choose among its roles because of a wrong condition.
The fixed version is 0.3.18. Hope that this time for good :)

**Comment by anthoneous** [comment]
This version has resolved the issue!

**Comment by venth** [comment]
Thank you for your patience, @anthoneous. The issue was hard to find.
