### ISSUE TITLE
Error: Issues during redirection to aws roles page. The error response <Response [401]>

### ISSUE THREAD

**Issue by leoww11Ptr** [venth/aws-adfs#57]
aws-adfs version: 0.4.0
python: tried on 2.7,3.4, and 3.6
urllib3 version: (1.10.2)
setup: Duo 2FA, and multi-role account

I get this error after passing the 2FA with successful auth: "Going for aws roles".

Two requests follow: first being a POST to adfs with cookies set, which results in 302. the following request is a GET to adfs which "should" retrieve the aws sign in form, but does not in this case.

when using the --verbose option, I noticed that the redirection (see the logs) points to: ..../wia?loginToRp=urn:amazon:webservices 
instead of: 
.../IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices

any idea what might be causing this erroneous redirection_location?
------------------------------------------------------------------------------------------------------------------------------
2017-10-14 11:28:40,271 [connectionpool connectionpool.py:_make_request] [19156-MainProcess] [139651693283136-MainThread] - DEBUG: https://adfs.xwz.com:443 "POST /adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices HTTP/1.1" 302 0

2017-10-14 11:28:40,332 [connectionpool connectionpool.py:_make_request] [19156-MainProcess] [139651693283136-MainThread] - DEBUG: https://adfs.xwz.com:443 "GET /adfs/ls/wia?loginToRp=urn:amazon:webservices HTTP/1.1" 401 0

**Comment by venth** [comment]
Hi @leoww11Ptr, 

would you like to verify if a previous version works correctly? The previous version can be installed with: `pip install aws-adfs==<version to install>`.

If you could also share anonymized logs from version: 0.4.0 I would appreciate it. Please send the logs on my address: artur(dot)krysiak(dot)warszawa(at)gmail.com

**Comment by leoww11Ptr** [comment]
Logs delivered.
tried the following versions with no success: 0.3.0, 0.3.3, 0.3.9, 0.3.18

**Comment by venth** [comment]
Please try most recent version. There was a fix for windows machine delivered. I hope it will solve the issue for you as well.

**Comment by leoww11Ptr** [comment]
Thank you, I will.

**Comment by venth** [comment]
@leoww11Ptr any success with the most recent version?

**Comment by max-nearmap** [comment]
Hi @venth and @leoww11Ptr ,
having same issue on windows 10 with aws-adfs `v0.11.0`, logs are pretty consistent with @leoww11Ptr 's ones. Did you manage to solve the issue?
Cheers

**Comment by venth** [comment]
Unfortunately I didn’t manage to solve it. I don’t have access to windows machine. Perhaps do you want to use workaround with docker? I can provide Dockerfile or compose with aws-adfs installed, which will interact with windows and let you overcome currrent issue.

**Comment by max-nearmap** [comment]
ok tx @venth, please provide both
cheers

**Comment by max-nearmap** [comment]
@venth this is my contact max[dot]guglielmi[at]nearmap[dot]com
cheers

**Comment by abohne** [comment]
Any progress on this issue?  I'm running into it here.
aws-adfs (0.12.0)
duo mfa

Our setup worked fine with aws-adfs until we enabled duo.

**Comment by venth** [comment]
Hi,

Sorry for the lack of response. I was pretty busy. Now, I started my vacations, so I count to have more time for aws-adfs.

**Comment by abohne** [comment]
@venth Any updates here?

**Comment by abohne** [comment]
@venth ?

**Comment by venth** [comment]
Sorry for the delay. During summer time I’ve checked few scenarios. Unfortunately none of them gave me a clue about the cause of your trouble. Perhaps we could meet over zoom or teamwork to nail the issue?

**Comment by abohne** [comment]
I'd be happy to do a zoom session with you.

**Comment by mighteemouse** [comment]
I am running into this 401 issue after Duo MFA on Windows as well. Is there a workaround in Docker at this time?

**Comment by slyoldfox** [comment]
@mighteemouse we have put together a docker image for our employees that use windows. 

```
docker run -it --rm -v %userprofile%/.aws:/root/.aws beforeach/adfs:1.12.2 login --adfs-host your.sts.host.name --profile yourprofile --region us-west-1  --session-duration 14400
```

Note that we don't provide support for this image in anyway way and use it at your own risk.

**Comment by copperorange** [comment]
@FixItDad I figured I get back to this and I have to say I think that worked. On the Windows desktop, it was fine as is but on a Mac, I changed the header and I think it is far more consistent now. I will try and find time to dig in deeper.

**Comment by Dobatymo** [comment]
Encountering this issue as well after confirming 2FA with Duo.
aws-adfs 1.24.5
Python 3.7.4
Windows 10

**Comment by hcsyash** [comment]
Getting same issue on both MacX and Windows :- 

Response:
            * status: 401
**Error: Issues during redirection to aws roles page. The error response <Response [401]>**

Provider : ADFS
2FA : DUO
aws-adfs : 1.24.5
Python : 3.9.0
OS : Windows 10 & Mac Catalina

Help anyone ? @venth @FixItDad @slyoldfox @copperorange

**Comment by pdecat** [comment]
The work-around is usually to also pass `--no-sspi` to `aws-adfs login`.

**Comment by trehman-sb** [comment]
I was having this issue in Python 3.8.7 on Windows 10. Passing `--no-sspi` resolved it for me.
