### ISSUE TITLE
Role arn passed as parameter to the login method

### ISSUE THREAD

**Issue by giafar** [venth/aws-adfs#66]
Hi,
is not possibile to automate the login process to aws if the saml assertion has more than one role arn because of the role_chooser requires user prompt.
As an enachment the login method could have a role_arn input parameter passed to the role_chooser and in case of it is in the principal_roles collection it is returned as the one choosen.

Thanks for the great job !

**Comment by connesc** [comment]
Note that the role is only prompted for the first login, which also prompts for user credentials anyway. Once the profile is created, the role is stored and not prompted anymore.

**Comment by giafar** [comment]
Yes you are right but in a automated building process I could switch from one role to another without user prompt and the role, at the moment, is not a param.

**Comment by giafar** [comment]
Thanks to Artur that merged the pull request #67

**Comment by venth** [comment]
Released with version 0.5.0. Sorry @giafar that incorporating the change took so long.
