### ISSUE TITLE
How to use "role-arn" parameter?

### ISSUE THREAD

**Issue by yermulnik** [venth/aws-adfs#70]
There is a new `--role-arn TEXT                 Predefined role arn to select` parameter in recent release, but there's no mentions in the code except the `login.py` and `README.md`. So it's not clear how to use it and what value (str, pattern, regex, etc) it expects.

**Comment by venth** [comment]
You’re right. Do you think that improving the help by an example would help to clear up the uncertainty?

**Comment by yermulnik** [comment]
It definitely would. And a use case would help to understand what this parameter is for. E.g. user can specify which exact role to choose/list by default or which role will be selected/listed by default (I'm not sure I got this parameter's purpose correctly).
By the way we might benefit from this parameter to take the role name only instead of role's arn at large: it's a bit easier to remember the role name comparing to long arn.
Thanks

**Comment by venth** [comment]
So, I believe we have here two issues:
- first about documentation improvement and
- second about extending login by additional parameter `—role-name`

**Comment by yermulnik** [comment]
Yup, exactly! But I'd say `--role-arn` could be replaced with `--role-name` entirely as I suppose most of the people to prefer `name` comparing to `arn` as role arn always consists of a _static_ and _custom_ parts: `arn:aws:iam::<account_id>:role/` and `<role_name>` respectively. One another use case from my personal practice: I use `aws-adfs` to authenticate against a bunch of AWS accounts (in one aws organization) with different types of roles and most of the time I need to use some specific role in several or all of the accounts. So I'd definitely benefit from specifying just a role-name to be assumed in several or all of the accounts returned by adfs auth. For now I have to use my local patches for `aws-adfs` to list only specific roles in accounts and to assume those in batch.

And thanks a lot for the job you do developing this great tool!

**Comment by venth** [comment]
@yermulnik, I've created #73 'Extending login by additional parameter —role-name' to move the discussion about --role-name parameter behavior to separate issue.

**Comment by venth** [comment]
Released with version 0.6.1

**Comment by venth** [comment]
Does it look good? Could you close it?

**Comment by yermulnik** [comment]
Oh, excuses. Yes, it looks good now. Thank you.
