### ISSUE TITLE
Duo authenticator status code calling

### ISSUE THREAD

**Issue by varxy20k** [venth/aws-adfs#80]
Hi, I'm trying to use this but I have my duo settings to call my phone by default instead of sending a push notification, because I don't want to install the duo application on my cellphone. The status code in that case is "calling" instead of "pushed", so I'm thinking this can be fixed by also accepting a status code of "calling".

https://github.com/venth/aws-adfs/blob/45b99291977fa5170e246e08435435d166cd9e20/aws_adfs/_duo_authenticator.py#L218

I'll try to come up with a pull request.

**Comment by KyleJamesWalker** [comment]
Fixed in #83

**Comment by venth** [comment]
Delivered with the version: 0.9.1
