### ISSUE TITLE
Incorporating the new CLI/API session duration functionality

### ISSUE THREAD

**Issue by steveubiera** [venth/aws-adfs#82]
AWS recently introduced the ability to extend Federated CLI/API session duration:

https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/

Is this a feature that can be incorporated?

**Comment by venth** [comment]
There is an attempt which result is presented on a very old branch: https://github.com/venth/aws-adfs/tree/feature/STS-token-duration
I think that now, I can integrate it into source code. The token duration is set by value got from adfs server.

Linked issues:
* https://github.com/venth/aws-adfs/pull/36
* https://github.com/venth/aws-adfs/issues/17

**Comment by anthoneous** [comment]
Should be done in the new PR:
https://github.com/venth/aws-adfs/pull/84

**Comment by venth** [comment]
Delivered in the version 0.9.0

**Comment by steveubiera** [comment]
Awesome!
