### ISSUE TITLE
Default Profile

### ISSUE THREAD

**Issue by KyleJamesWalker** [venth/aws-adfs#86]
Why does the following line us `default123`?

https://github.com/venth/aws-adfs/blob/47fdb05c0e7bce10012074f746ca7eec285082dd/aws_adfs/prepare.py#L40

The documentation states it should use `default`, it seems like the tool is using `default` for most people in our office, except one person it always uses `default123` unless the `--profile` option is passed.

**Comment by KyleJamesWalker** [comment]
Update: It looks like if you wipe out the profiles (or don't have a default) it will use `default123` but if there's a default it will use default.  **possibly**

**Comment by kwhitlock** [comment]
Looks like it if no profile is specified, it tries to find `default123` in your profile, which, if not present will get caught by the exception, where by it will try to use the profile `default` if present.

**Comment by KyleJamesWalker** [comment]
The odd thing is I deleted the default123 and it keeps coming back which was driving me crazy.
