### ISSUE TITLE
Using the environment and stdin parameters

### ISSUE THREAD

**Issue by leonardo-test** [venth/aws-adfs#91]
I'm not sure if this is normal but when I try to use the --env parameter it goes to Username and doesn't automatically login. I've already set my username and password parameters. 

aws-adfs login --adfs-host=example --no-ssl-verification --role-arn arn:aws:iam::example --env

`/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-04-19 11:39:03,069 [authenticator authenticator.py:authenticate] [4342-MainProcess] [139642134476544-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Username: `

Also, when I try to use the stdin parameters it says Aborted? 

echo -e "$username\n$password" | aws-adfs login --adfs-host=example --no-ssl-verification --role-arn arn:aws:iam::example --stdin

`/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-04-19 11:37:33,191 [authenticator authenticator.py:authenticate] [4265-MainProcess] [140101450082048-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Username: Aborted!`

**Comment by pquackenbush** [comment]
I found in `login.login` unless you are using the `--authfile` flag, `_get_user_credentials(config)` will always be called.  My suggestion would be to convert the chain of ifs into a single if-elif-elif-else.  This allowed me to successfully log into our adfs-host.

Possible problem code:
```python
    if assertion is None:
        if stdin:
            username, password = _stdin_user_credentials()
        if env:
            username, password = _env_user_credentials()
        if authfile:
            username, password = _file_user_credentials(config.profile, authfile)
        else:
            username, password = _get_user_credentials(config)
```
